services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    env_file:
        - .env
    build:
      context: ./api
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://${USERNAME}:${PASSWORD}@db:5432/${DATABASE}
      RAILS_LOG_TO_STDOUT: "1"
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    ports:
      - "3001:3000"   # Nextと被らないように3001
    tty: true

  web:
    image: node:20-bookworm-slim
    working_dir: /app
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CLOUDFLARE_DEV=0
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"

volumes:
  pgdata:
  bundle:
  web_node_modules:
